// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Skincare_Product_Sales_System_Infrastructure.Data;

#nullable disable

namespace Skincare_Product_Sales_System_Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250215140631_SeedSkinAnswerData")]
    partial class SeedSkinAnswerData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Tẩy trang",
                            CategoryStatus = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Sữa rửa mặt",
                            CategoryStatus = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Tẩy tế bào chết",
                            CategoryStatus = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Toner",
                            CategoryStatus = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Serum",
                            CategoryStatus = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Dưỡng ẩm",
                            CategoryStatus = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Kem chống nắng",
                            CategoryStatus = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Mặt nạ",
                            CategoryStatus = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Kem mắt",
                            CategoryStatus = 0
                        });
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentStatus")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("StaffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StaffId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("ExpiredDate")
                        .HasColumnType("date");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductStatus")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SkinTypeId")
                        .HasColumnType("int");

                    b.Property<string>("StaffId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("StepRoutineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SkinTypeId");

                    b.HasIndex("StaffId");

                    b.HasIndex("StepRoutineId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SkinTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SkinTypeId");

                    b.ToTable("SkinAnswers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnswerText = "Đổ dầu nhiều, bóng nhờn",
                            QuestionId = 1,
                            SkinTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            AnswerText = "Chữ T hơi dầu, má bình thường",
                            QuestionId = 1,
                            SkinTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            AnswerText = "Khô căng, có thể bong tróc",
                            QuestionId = 1,
                            SkinTypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            AnswerText = "Ổn định, không dầu cũng không khô",
                            QuestionId = 1,
                            SkinTypeId = 4
                        },
                        new
                        {
                            Id = 5,
                            AnswerText = "Rất bóng, đặc biệt ở vùng trán và mũi",
                            QuestionId = 2,
                            SkinTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            AnswerText = "Chỉ bóng ở vùng chữ T, còn lại bình thường",
                            QuestionId = 2,
                            SkinTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            AnswerText = "Không bóng chút nào, có khi còn bong tróc",
                            QuestionId = 2,
                            SkinTypeId = 3
                        },
                        new
                        {
                            Id = 8,
                            AnswerText = "Hầu như không bóng, vẫn giữ độ ẩm tốt",
                            QuestionId = 2,
                            SkinTypeId = 4
                        },
                        new
                        {
                            Id = 9,
                            AnswerText = "Rất nhiều dầu, đặc biệt là vùng chữ T",
                            QuestionId = 3,
                            SkinTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            AnswerText = "Chỉ vùng chữ T có dầu, hai bên má thì khô",
                            QuestionId = 3,
                            SkinTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            AnswerText = "Không có dầu, thường khô căng",
                            QuestionId = 3,
                            SkinTypeId = 3
                        },
                        new
                        {
                            Id = 12,
                            AnswerText = "Ít dầu, da luôn cân bằng",
                            QuestionId = 3,
                            SkinTypeId = 4
                        },
                        new
                        {
                            Id = 13,
                            AnswerText = "Nhanh chóng đổ dầu trở lại",
                            QuestionId = 4,
                            SkinTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            AnswerText = "Một số vùng đổ dầu, một số vùng khô",
                            QuestionId = 4,
                            SkinTypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            AnswerText = "Căng rát, thậm chí bong tróc",
                            QuestionId = 4,
                            SkinTypeId = 3
                        },
                        new
                        {
                            Id = 16,
                            AnswerText = "Mềm mại, thoải mái",
                            QuestionId = 4,
                            SkinTypeId = 4
                        },
                        new
                        {
                            Id = 17,
                            AnswerText = "Không bao giờ",
                            QuestionId = 5,
                            SkinTypeId = 1
                        },
                        new
                        {
                            Id = 18,
                            AnswerText = "Thỉnh thoảng, ở hai bên má",
                            QuestionId = 5,
                            SkinTypeId = 2
                        },
                        new
                        {
                            Id = 19,
                            AnswerText = "KRất hay bong tróc, nhất là quanh mũi và miệng",
                            QuestionId = 5,
                            SkinTypeId = 3
                        },
                        new
                        {
                            Id = 20,
                            AnswerText = "Hiếm khi bong tróc",
                            QuestionId = 5,
                            SkinTypeId = 4
                        },
                        new
                        {
                            Id = 21,
                            AnswerText = "Đổ dầu rất nhiều, da lúc nào cũng ẩm ướt",
                            QuestionId = 6,
                            SkinTypeId = 1
                        },
                        new
                        {
                            Id = 22,
                            AnswerText = "Đổ dầu ở vùng chữ T, hai bên má bình thường",
                            QuestionId = 6,
                            SkinTypeId = 2
                        },
                        new
                        {
                            Id = 23,
                            AnswerText = "Không đổ dầu, thậm chí còn khô hơn",
                            QuestionId = 6,
                            SkinTypeId = 3
                        },
                        new
                        {
                            Id = 24,
                            AnswerText = "Chỉ hơi nhờn nhẹ, nhưng không quá nhiều",
                            QuestionId = 6,
                            SkinTypeId = 4
                        },
                        new
                        {
                            Id = 25,
                            AnswerText = "Rất dễ bị mụn, đặc biệt là vùng trán và cằm",
                            QuestionId = 7,
                            SkinTypeId = 1
                        },
                        new
                        {
                            Id = 26,
                            AnswerText = "Thỉnh thoảng bị mụn ở vùng chữ T",
                            QuestionId = 7,
                            SkinTypeId = 2
                        },
                        new
                        {
                            Id = 27,
                            AnswerText = "Hiếm khi bị mụn nhưng dễ bị kích ứng",
                            QuestionId = 7,
                            SkinTypeId = 3
                        },
                        new
                        {
                            Id = 28,
                            AnswerText = "Ít bị mụn",
                            QuestionId = 7,
                            SkinTypeId = 4
                        });
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinCareRoutine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoutineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SkinTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalSteps")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SkinTypeId");

                    b.ToTable("SkinCareRoutines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Giúp kiểm soát dầu, ngăn ngừa mụn và giữ ẩm nhẹ nhàng.",
                            RoutineName = "Lộ trình cho da dầu",
                            SkinTypeId = 1,
                            Status = 0,
                            TotalSteps = 6
                        },
                        new
                        {
                            Id = 2,
                            Description = "Dưỡng ẩm sâu, bảo vệ da khỏi bong tróc và mất nước.",
                            RoutineName = "Lộ trình cho da khô",
                            SkinTypeId = 2,
                            Status = 0,
                            TotalSteps = 6
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cân bằng dầu vùng chữ T và giữ ẩm vùng khô.",
                            RoutineName = "Lộ trình cho da hỗn hợp",
                            SkinTypeId = 3,
                            Status = 0,
                            TotalSteps = 6
                        },
                        new
                        {
                            Id = 4,
                            Description = "Duy trì độ ẩm và bảo vệ da trước tác nhân môi trường.",
                            RoutineName = "Lộ trình cho da thường",
                            SkinTypeId = 4,
                            Status = 0,
                            TotalSteps = 6
                        },
                        new
                        {
                            Id = 5,
                            Description = "Làm dịu da, giảm kích ứng và tăng cường hàng rào bảo vệ.",
                            RoutineName = "Lộ trình cho da nhạy cảm",
                            SkinTypeId = 5,
                            Status = 0,
                            TotalSteps = 6
                        });
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkinQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionText = "Khi thức dậy vào buổi sáng, bạn cảm thấy da mình thế nào?"
                        },
                        new
                        {
                            Id = 2,
                            QuestionText = "Bạn có thường xuyên cảm thấy da mình bóng nhờn vào giữa ngày không?"
                        },
                        new
                        {
                            Id = 3,
                            QuestionText = "Da bạn có nhiều dầu vào cuối ngày không?"
                        },
                        new
                        {
                            Id = 4,
                            QuestionText = "Khi rửa mặt xong, bạn cảm thấy da mình thế nào?"
                        },
                        new
                        {
                            Id = 5,
                            QuestionText = "Da bạn có hay bị bong tróc, ngứa vào mùa lạnh không?"
                        },
                        new
                        {
                            Id = 6,
                            QuestionText = "Khi trời nóng, da bạn có đổ dầu nhiều hơn bình thường không?"
                        },
                        new
                        {
                            Id = 7,
                            QuestionText = "Bạn có hay bị mụn không?"
                        });
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinTest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SkinTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SkinTypeId");

                    b.ToTable("SkinTests");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinTestAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnswerId")
                        .HasColumnType("int");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SkinTestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SkinTestId");

                    b.ToTable("SkinTestAnswers");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SkinTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SkinTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SkinTypeName = "Da dầu"
                        },
                        new
                        {
                            Id = 2,
                            SkinTypeName = "Da hỗn hợp"
                        },
                        new
                        {
                            Id = 3,
                            SkinTypeName = "Da khô"
                        },
                        new
                        {
                            Id = 4,
                            SkinTypeName = "Da thường"
                        });
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.StepRoutine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoutineId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StepDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("StepRoutines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RoutineId = 1,
                            Status = 0,
                            StepDescription = "Tẩy trang để loại bỏ dầu và bụi bẩn",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 2,
                            RoutineId = 1,
                            Status = 0,
                            StepDescription = "Rửa mặt với sữa rửa mặt kiềm dầu",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 3,
                            RoutineId = 1,
                            Status = 0,
                            StepDescription = "Dùng toner giúp kiểm soát dầu",
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 4,
                            RoutineId = 1,
                            Status = 0,
                            StepDescription = "Sử dụng serum giảm dầu, ngừa mụn",
                            StepNumber = 4
                        },
                        new
                        {
                            Id = 5,
                            RoutineId = 1,
                            Status = 0,
                            StepDescription = "Dưỡng ẩm nhẹ, không gây bít tắc",
                            StepNumber = 5
                        },
                        new
                        {
                            Id = 6,
                            RoutineId = 1,
                            Status = 0,
                            StepDescription = "Thoa kem chống nắng kiềm dầu",
                            StepNumber = 6
                        },
                        new
                        {
                            Id = 7,
                            RoutineId = 2,
                            Status = 0,
                            StepDescription = "Dùng dầu tẩy trang để cấp ẩm",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 8,
                            RoutineId = 2,
                            Status = 0,
                            StepDescription = "Rửa mặt với sữa rửa mặt dịu nhẹ",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 9,
                            RoutineId = 2,
                            Status = 0,
                            StepDescription = "Dùng toner cấp ẩm",
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 10,
                            RoutineId = 2,
                            Status = 0,
                            StepDescription = "Sử dụng serum cấp nước",
                            StepNumber = 4
                        },
                        new
                        {
                            Id = 11,
                            RoutineId = 2,
                            Status = 0,
                            StepDescription = "Dưỡng ẩm chuyên sâu",
                            StepNumber = 5
                        },
                        new
                        {
                            Id = 12,
                            RoutineId = 2,
                            Status = 0,
                            StepDescription = "Thoa kem chống nắng dưỡng ẩm",
                            StepNumber = 6
                        },
                        new
                        {
                            Id = 13,
                            RoutineId = 3,
                            Status = 0,
                            StepDescription = "Tẩy trang để loại bỏ dầu thừa và bụi bẩn",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 14,
                            RoutineId = 3,
                            Status = 0,
                            StepDescription = "Rửa mặt với sữa rửa mặt dịu nhẹ cân bằng",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 15,
                            RoutineId = 3,
                            Status = 0,
                            StepDescription = "Dùng toner giúp cân bằng da",
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 16,
                            RoutineId = 3,
                            Status = 0,
                            StepDescription = "Sử dụng serum dưỡng ẩm nhẹ",
                            StepNumber = 4
                        },
                        new
                        {
                            Id = 17,
                            RoutineId = 3,
                            Status = 0,
                            StepDescription = "Dưỡng ẩm dạng gel hoặc lotion",
                            StepNumber = 5
                        },
                        new
                        {
                            Id = 18,
                            RoutineId = 3,
                            Status = 0,
                            StepDescription = "Thoa kem chống nắng có độ ẩm vừa phải",
                            StepNumber = 6
                        },
                        new
                        {
                            Id = 19,
                            RoutineId = 4,
                            Status = 0,
                            StepDescription = "Tẩy trang với dầu hoặc nước micellar",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 20,
                            RoutineId = 4,
                            Status = 0,
                            StepDescription = "Rửa mặt với sữa rửa mặt nhẹ nhàng",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 21,
                            RoutineId = 4,
                            Status = 0,
                            StepDescription = "Dùng toner cấp ẩm hoặc làm dịu da",
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 22,
                            RoutineId = 4,
                            Status = 0,
                            StepDescription = "Sử dụng serum tăng cường bảo vệ da",
                            StepNumber = 4
                        },
                        new
                        {
                            Id = 23,
                            RoutineId = 4,
                            Status = 0,
                            StepDescription = "Dưỡng ẩm dạng kem hoặc gel phù hợp",
                            StepNumber = 5
                        },
                        new
                        {
                            Id = 24,
                            RoutineId = 4,
                            Status = 0,
                            StepDescription = "Thoa kem chống nắng SPF 30+",
                            StepNumber = 6
                        },
                        new
                        {
                            Id = 25,
                            RoutineId = 5,
                            Status = 0,
                            StepDescription = "Tẩy trang dịu nhẹ, tránh sản phẩm có cồn",
                            StepNumber = 1
                        },
                        new
                        {
                            Id = 26,
                            RoutineId = 5,
                            Status = 0,
                            StepDescription = "Rửa mặt với sữa rửa mặt không chứa hương liệu",
                            StepNumber = 2
                        },
                        new
                        {
                            Id = 27,
                            RoutineId = 5,
                            Status = 0,
                            StepDescription = "Dùng toner không chứa cồn",
                            StepNumber = 3
                        },
                        new
                        {
                            Id = 28,
                            RoutineId = 5,
                            Status = 0,
                            StepDescription = "Sử dụng serum phục hồi da",
                            StepNumber = 4
                        },
                        new
                        {
                            Id = 29,
                            RoutineId = 5,
                            Status = 0,
                            StepDescription = "Dưỡng ẩm chuyên biệt cho da nhạy cảm",
                            StepNumber = 5
                        },
                        new
                        {
                            Id = 30,
                            RoutineId = 5,
                            Status = 0,
                            StepDescription = "Thoa kem chống nắng vật lý dịu nhẹ",
                            StepNumber = 6
                        });
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("Wallet")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.Comment", b =>
                {
                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.User", "Customer")
                        .WithMany("Comments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.Order", b =>
                {
                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.User", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.User", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.OrderDetail", b =>
                {
                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.Product", b =>
                {
                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.SkinType", "SkinType")
                        .WithMany("Products")
                        .HasForeignKey("SkinTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.User", "Staff")
                        .WithMany("Products")
                        .HasForeignKey("StaffId");

                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.StepRoutine", "StepRoutine")
                        .WithMany("Products")
                        .HasForeignKey("StepRoutineId");

                    b.Navigation("Category");

                    b.Navigation("SkinType");

                    b.Navigation("Staff");

                    b.Navigation("StepRoutine");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinAnswer", b =>
                {
                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.SkinQuestion", "SkinQuestion")
                        .WithMany("SkinAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.SkinType", "SkinType")
                        .WithMany("SkinAnswer")
                        .HasForeignKey("SkinTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkinQuestion");

                    b.Navigation("SkinType");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinCareRoutine", b =>
                {
                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.SkinType", "SkinType")
                        .WithMany("SkinCareRoutines")
                        .HasForeignKey("SkinTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SkinType");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinTest", b =>
                {
                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.User", "Customer")
                        .WithMany("SkinTests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.SkinType", "SkinType")
                        .WithMany("SkinTests")
                        .HasForeignKey("SkinTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SkinType");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinTestAnswer", b =>
                {
                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.SkinAnswer", "SkinAnswer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.SkinQuestion", "SkinQuestion")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.SkinTest", "SkinTest")
                        .WithMany()
                        .HasForeignKey("SkinTestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SkinAnswer");

                    b.Navigation("SkinQuestion");

                    b.Navigation("SkinTest");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.StepRoutine", b =>
                {
                    b.HasOne("Skincare_Product_Sales_System_Domain.Entities.SkinCareRoutine", "Routine")
                        .WithMany("StepRoutines")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.Product", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinCareRoutine", b =>
                {
                    b.Navigation("StepRoutines");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinQuestion", b =>
                {
                    b.Navigation("SkinAnswers");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.SkinType", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SkinAnswer");

                    b.Navigation("SkinCareRoutines");

                    b.Navigation("SkinTests");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.StepRoutine", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Skincare_Product_Sales_System_Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Products");

                    b.Navigation("SkinTests");
                });
#pragma warning restore 612, 618
        }
    }
}
